version: '3.3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: elixir:latest
    env_file: .env
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "mix deps.get && mix ecto.create && mix phx.server"
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  postgres_data:
